name: Build project
on: [push]
jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: Android
    steps:
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-xFME-${{env.TARGET_PLATFORM}}
        restore-keys: |
          Library-xFME-
          Library-
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: ${{env.TARGET_PLATFORM}}
        unityVersion: auto
    - uses: actions/upload-artifact@v2
      with:
        name: "Android_Build"
        path: build
